import Home from '@/components/home'
import MarketPlace from '@/components/marketplace';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Home | MB-Walmart",
  description: "Generated by Xaad Ali",
  icons: {
    icon: {
      url: "/logo-walmart.png",
      type: "image/png",
    },
    shortcut: { url: "/logo-walmart.png", type: "image/png" },
  },
};

const page = () => {
  return (
    <MarketPlace />
  )
}

export default page