export const CardsData = [
    {
        icon:"/building.svg",
        heading:"Revenue Share",
        description:"All fees generated by our platform will be shared with $COOKER holders, check detailed info about revenue share on this link."
    },
    {
        icon:"/connect.svg",
        heading:"0% Fee for Holders",
        description:"By holding $COOKER tokens you will also be able to use our services with 0% fee."
    },
    {
        icon:"/token.svg",
        heading:"Tokenomics",
        description:"Token name - $COOKER",
        descriptionOne:"Supply - 100,000,000",
        descriptionTwo:"Taxes - 3% Buy / 3% Sell",
        descriptionThree:"Tokens on Initial Liquidity - 90%"
    }
]